nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - .:/var/www/sleepcoffe
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php

php:
    build: docker/php/.
    ports:
        - "9000:9000"
    volumes:
        - .:/var/www/sleepcoffe
    links:
        - mysql

mysql:
    image: mariadb
    ports:
        - 3366:3306
    volumes:
        - "./.data/db:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: root
        TERM: linux